desc = {
    "Urban Fabric": "Urban fabric refers to land shaped by buildings, roads, public spaces, and infrastructure. It forms the physical structure and visual character of an urban area. It includes residential, commercial, institutional, and mixed-use developments. Its pattern is influenced by street networks, building density, plot sizes, and open spaces. A well-planned urban fabric supports connectivity, accessibility, and efficient land use. It also contributes to the identity and livability of a city.",

    "Mixed Forest": "Mixed forest land is an area covered by a combination of different types of trees and vegetation. It usually contains both deciduous and evergreen tree species. Mixed forests provide important habitats for birds, animals, and other wildlife. They help improve air quality, conserve soil, and regulate the local climate. These areas support biodiversity and maintain ecological balance. Mixed forests can also provide recreational and environmental benefits.",

    "Agricultural Land": "Agricultural land is primarily used for growing crops and cultivating plants. It may include farmland, orchards, plantations, and cultivated fields. These areas play an important role in supporting food production and rural livelihoods. The land is generally characterized by open spaces with seasonal or permanent vegetation. Irrigation, soil quality, and climate influence agricultural activities. Proper management helps maintain soil fertility and sustainable production.",

    "Built-up Land": "Built-up land consists of areas occupied by buildings and constructed structures. It includes residential, commercial, industrial, institutional, and other developed areas. Roads, parking spaces, and supporting infrastructure are also commonly associated with built-up land. These areas generally have a high concentration of human activities and development. The extent of built-up land reflects the level of urbanization in a region. Proper planning ensures efficient and sustainable development.",

    "Open/Vacant Land": "Open or vacant land refers to undeveloped areas with limited or no permanent structures. It may consist of bare soil, grassland, scrub, or unused plots. Such land can occur within urban areas as well as on their outskirts. Vacant land may provide opportunities for future development and public facilities. It can also support temporary vegetation and ecological functions. Proper management can help prevent waste dumping and unplanned encroachment.",

    "Water Bodies": "Water bodies include rivers, lakes, ponds, reservoirs, canals, and other surface-water areas. They are important sources of water for ecological, domestic, and economic activities. Water bodies provide habitats for aquatic plants, animals, and birds. They also contribute to groundwater recharge and local environmental balance. Urban and rural water bodies can provide recreational and aesthetic value. Protecting these areas from pollution is essential for maintaining water quality.",

    "Scrub Land": "Scrub land is characterized by low-growing shrubs, bushes, grasses, and scattered trees. It commonly develops in areas with limited rainfall or disturbed vegetation. Scrub areas provide shelter and food for various birds and small animals. They also help reduce soil erosion and provide basic ecological functions. The density and type of vegetation vary depending on soil and climatic conditions. Proper conservation can support biodiversity and natural regeneration."
}